627 add custom class field to categories
grandnode/grandnode pull request #653
Opened 2019-10-14 11:10 UTC by BeliaevFiodor

Resolves #627  
Type: feature

## Issue
it is ready

## Solution

## Breaking changes
custom class field to categories added

## Testing
open a category in admin page. So it is custom class fied appears at bottom of list

2019-10-14 11:39 UTC, PatrykPorabik commented
Hi,
I'm not able to merge this PR with the last change that you've made in "Fix" commit. Why have you removed the Settings.txt from the file?

2019-10-14 12:30 UTC, BeliaevFiodor commented
Hi.
I needed to reinstall DB and it was not possible without it. Now it is fixed

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пн, 14 окт. 2019 г. в 14:39, Patryk Porabik <notifications@github.com>:

> Hi,
> I'm not able to merge this PR with the last change that you've made in
> "Fix" commit. Why have you removed the Settings.txt from the file?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/grandnode/grandnode/pull/653?email_source=notifications&email_token=AKZV4LTT4RLH2XK3QIIVNO3QORLA3A5CNFSM4JANWDNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBEJJAY#issuecomment-541627523>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKZV4LRYSHZGLQP2TNAF5ZTQORLA3ANCNFSM4JANWDNA>
> .
>

2019-10-14 13:06 UTC, PatrykPorabik commented
settings.txt is a crucial file for store, it can be published on GitHub. I meant about change in commit file where you delete file from excluding, not about adding it to PR. Just restore the removed part of this file and send PR again.

2019-10-17 06:08 UTC, BeliaevFiodor commented
I'm sorry for this delay

2019-10-17 06:40 UTC, PatrykPorabik commented
Hi Fiodor, it's still not about that change. Please check the default Grand.Web.csproj and make your file the same. Send us just changes listed in your first commit.

2019-10-17 07:17 UTC, BeliaevFiodor commented
I just get Grand.Web.csproj from 1-st commit. is it enough?

2019-10-21 05:41 UTC, PatrykPorabik commented
Fiodor, what about frontend? If we add class in admin panel, what will happen? It should add this class to created category. This class should be used when user would like to add some action to it. For example create mega menu without additional plugins.

2019-10-22 12:40 UTC, BeliaevFiodor commented
Hello.
I just had pull a new commit. Class field is receiving in frontend now. But I afraid I can lost some models, where this fiels is necessary. And I didn't undestand where I should use it. In a case of CustomerAction Class field using while the full html string returning to controller. But Category is drowing in some kind of widget, which I didn't found. 
And I have some ideas about css. If we should use it not only in categories and in customer actions, perhaps the better way is to store styles and classes in separate tables in DB? It allow us to create such kind of styles and classes library to make interface more frendly?

2019-10-22 13:27 UTC, PatrykPorabik requested changes
I've left comments in the files which should not appear in commits. In general in pull request, not only in this one, including Settings.txt file is dangerous, because you share your sensitive data with audience. Then, if I try to install GrandNode with this PR included, I won't be able to run it. I will receive the error, because I don't have this db created locally. If you don't know how to remove it or ignore it during the sending PR, please ask @dborovsky for help, he always does it correctly. 

In the case of frontend - this class should be added to the class=" " attribute of each hyperlink of categories. This is enough. There is no need to create additional tables. And it's just about categories. It just should appear here:
![image](https://user-images.githubusercontent.com/16773025/67290071-e3e79480-f4df-11e9-8730-25d2df610f88.png)

2019-10-22 13:27 UTC, PatrykPorabik commented on Grand.Web/App_Data/InstalledPlugins.txt
> +DiscountRequirements.Standard
Please remove this whole file from commit.

2019-10-22 13:27 UTC, PatrykPorabik commented on Grand.Web/App_Data/Settings.txt
> +DataProvider: mongodb
That file also should be removed from the commit, as I wrote few times.

2019-10-22 13:27 UTC, PatrykPorabik commented on Grand.Web/Grand.Web.csproj
> +</Project>
That change also is unnecessary.

2019-10-23 07:21 UTC, BeliaevFiodor commented
it seems to be done.

2019-10-28 06:20 UTC, BeliaevFiodor commented
Hi. I think i did it. But can not turn off red label at "change requested". But it looks like ready

2019-10-28 09:08 UTC, PatrykPorabik commented on Grand.Web/App_Data/Localization/Upgrade/EN_410_420.nopres.xml
> +  <LocaleResource Name="Admin.Catalog.Categories.Fields.Class">
You've added this resources to the wrong file. It's file related for upgrade from 4.10 to 4.20 version of GrandNode. You should add this code to the upgrade file 4.50 to 4.60.

2019-10-28 09:26 UTC, BeliaevFiodor commented
ok. I did it

2019-10-28 09:29 UTC, PatrykPorabik commented on Grand.Web/App_Data/Localization/Upgrade/EN_410_420.nopres.xml
> +  <LocaleResource Name="Admin.Catalog.Categories.Fields.Class">
And this one should be deleted...

2020-07-03 08:35 UTC, closed without merging