#898 add possibility edit customrobots.txt
grandnode/grandnode pull request #917
Opened 2020-09-02 20:22 UTC by dborovsky

2020-09-03 19:35 UTC, dborovsky commented
#898

2020-09-04 06:20 UTC, PatrykPorabik requested changes
@dborovsky please look at my comments.

2020-09-04 06:20 UTC, PatrykPorabik commented on Grand.Web/App_Data/Localization/Upgrade/EN_470_480.nopres.xml
> +  <LocaleResource Name="Admin.System.CustomRobotTxt">
Again wrong resource strings. You've forgot to add <Value> tag, please look at the resource string in the previous line.

2020-09-04 06:20 UTC, PatrykPorabik commented on Grand.Web/App_Data/Localization/Upgrade/EN_470_480.nopres.xml
> +    Custom robot.txt
To maintain consistency I would stay in the robots.txt nomenclature.

2020-09-04 06:20 UTC, PatrykPorabik commented on Grand.Web/Areas/Admin/Views/Common/CustomRobotTxt.cshtml
> +                            extraKeys: { "Ctrl-Space": "autocomplete" }
Similarly here. It's useless in that case.

2020-09-04 06:20 UTC, PatrykPorabik commented on Grand.Web/Areas/Admin/Views/Common/CustomRobotTxt.cshtml
> +    pagebuilder.AddScriptParts(ResourceLocation.Head, "~/content/codemirror/edit/matchbrackets.js", excludeFromBundle: true);
As you correctly noticed, it's not possible to implement hints, so why have you added js and CSS resources for hints? :) It's enough to keep only codemirror.js and codemirror.css file.

2020-09-04 06:20 UTC, PatrykPorabik commented on .gitignore
> +Grand.Web/wwwroot/robots.custom.txt
Out of the box I would remove it.

2020-09-04 06:20 UTC, PatrykPorabik commented on Grand.Web/App_Data/Localization/defaultResources.grandres.xml
> +    Custom robot.txt
Again you've missed the <value> tag.

2020-09-04 06:20 UTC, PatrykPorabik commented on Grand.Web/App_Data/sitemap.config
> +        <siteMapNode SystemName="Custom robot.txt" grandResource="Admin.System.CustomRobotTxt" PermissionNames="ManageMaintenance" controller="Common" action="CustomRobotTxt" IconClass="fa fa-dot-cir
As previously, please keep the consistency in the nomenclature.

2020-09-04 12:02 UTC, merged